apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:sAcBtbpNHB15WQMlFtxuMZslVz8iY23s,iv:SbETEM8BPiK+pNsINBhQiuxnXNe9sV/XCPs5lNYxFi4=,tag:hbX0HM0gFwW5T1H+ceboXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1etvas2d04gjcylcld4j5asveqthhnrhy2uwmmjewsr728p2z3p4sqz7449
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eW9yUEFFcmpSbWZjV1lG
            NWcxWnBXMUVxQkNGd3RkVUpmazdXZENXc0JBCjhKNVYxc2hleFd3ZkgrSXRCWFV1
            Wjg5cW01ZGU4RVJxUHN0dnZFTHBTdkEKLS0tIEEyTmtqdkQ4K2tHaWF2T0tLUmUx
            bEZDOFlINWg2WTJJeEFEaENNMGQrd0EKVvGA7VvvYB0+NspzS9MG7/+94P7uJBNu
            lB+KIi3/WvERCvA3rgX6Y44KF0IOtA4cPjEtXpBFgUIWZLQWjTAbpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T22:02:11Z"
    mac: ENC[AES256_GCM,data:vcyD40/OeLcYoeJQRi1IuRoDvx/knEY1sDymQf2SUjtU2T8ZKFN+PcD4IyONO0CWie7XHdUrPzmH7xWiiJd9j4vwuLEcYw2b7pCtzus4RaoClfFicOZvDcXTPiu4XuLRU1JUFJOQknUZLAxununNBdY6HqFZ52Ybj/c1XKv8fx0=,iv:W6irHm48Sv2QdqYyiMbJwcz6mtsYG2Wlssc0fK3ap0Q=,tag:RA7otWkq/Esa8dmfnUQvyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
